#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : scrypt
Version  : 0.8.7
Release  : 5
URL      : https://files.pythonhosted.org/packages/1f/af/70a7cb4f27f1673bc8b6af3587545eb0327e5823ab96b1eb81b541fe087e/scrypt-0.8.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/1f/af/70a7cb4f27f1673bc8b6af3587545eb0327e5823ab96b1eb81b541fe087e/scrypt-0.8.7.tar.gz
Summary  : key derivation function and encryption utility
Group    : Development/Tools
License  : BSD-2-Clause
Requires: scrypt-license = %{version}-%{release}
Requires: scrypt-python = %{version}-%{release}
Requires: scrypt-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : openssl-dev

%description
=========================
Python scrypt_ bindings
=========================
This is a set of Python_ bindings for the scrypt_ key derivation
function.

%package license
Summary: license components for the scrypt package.
Group: Default

%description license
license components for the scrypt package.


%package python
Summary: python components for the scrypt package.
Group: Default
Requires: scrypt-python3 = %{version}-%{release}

%description python
python components for the scrypt package.


%package python3
Summary: python3 components for the scrypt package.
Group: Default
Requires: python3-core

%description python3
python3 components for the scrypt package.


%prep
%setup -q -n scrypt-0.8.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549122362
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/scrypt
cp LICENSE %{buildroot}/usr/share/package-licenses/scrypt/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/scrypt/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
